version: "3.8"
services:
  nginx:
    image: nginx:1.25
    container_name: bg_nginx
    ports:
      - "${HOST_PUBLIC_PORT:-8080}:80"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/templates/nginx.template.conf:ro
      - ./nginx/entrypoint.sh:/usr/local/bin/nginx-entrypoint.sh:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - BLUE_SERVICE_HOST=app_blue
      - GREEN_SERVICE_HOST=app_green
      - BLUE_SERVICE_PORT=${PORT}
      - GREEN_SERVICE_PORT=${PORT}
    entrypoint: ["/bin/sh","/usr/local/bin/nginx-entrypoint.sh"]
    networks:
      - bg_net
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    env_file:
      - .env
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "${HOST_BLUE_PORT:-8081}:${PORT}"
    networks:
      - bg_net

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    env_file:
      - .env
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "${HOST_GREEN_PORT:-8082}:${PORT}"
    networks:
      - bg_net

networks:
  bg_net:
    driver: bridge
